/**
 * The storage contract every backend implements.
 *
 * Three operations, and deliberately no `get`: nothing in PostGear reads media
 * back through the API. Browsers and social platforms fetch it from
 * `publicUrl()` directly — a CDN for S3, a static route for local disk — so
 * the API never proxies bytes it has already stored.
 */

/** Bytes in memory, or a file already on disk (a video straight from the upload). */
export type StorageBody = Buffer | { filePath: string; size: number };

export interface StorageBackend {
  readonly kind: 'local' | 's3';

  /** Stores an object. Keys are generated by `storage-keys.ts` and never reused. */
  put(key: string, body: StorageBody, contentType: string): Promise<void>;

  /** Removes an object. Succeeds when the object is already gone. */
  delete(key: string): Promise<void>;

  /** Where a browser or a platform can fetch the object. */
  publicUrl(key: string): string;
}

/** Nest injection token for the configured backend. */
export const STORAGE_BACKEND = Symbol('STORAGE_BACKEND');
